sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
    - 12
before_install: .travis/script-before-install.sh
before_script: .travis/script-before.sh
script: .travis/script-build.sh
after_success: .travis/script-after-success.sh
