import React from 'react'
import {
    HomeIcon,
    BuildIcon,
    SettingsIcon,
    AccountCircleIcon,
    EditIcon,
    InsertDriveFileIcon,
    FolderIcon,
    SubjectIcon,
    ChatIcon,
    LaunchIcon,
    ShoppingCartIcon,
    WebIcon,
    ImageIcon,
    DoneIcon,
    ViewListIcon,
    ViewModuleIcon,
    LabelIcon,
    BusinessIcon,
    EventIcon,
    SchoolIcon,
    ScheduleIcon,
    ShopIcon,
    BeachAccessIcon,
    GroupIcon,
    ThumbUpIcon,
    SettingsInputComponentIcon,
    TrainIcon,
    TrafficIcon,
    MailIcon,
    CardMembershipIcon,
    MoneyIcon,
    BarChartIcon,
    StoreIcon,
    HouseIcon,
    WorkIcon,
    LocalCafeIcon,
    SportsTennisIcon,
    AccessibleIcon,
    AccountBalanceIcon,
    DirectionsBoatIcon,
    FilterListIcon,
    CasinoIcon,
    SaveIcon,
    BookIcon,
    SearchIcon,
    BackupIcon,
    VideoSettingsIcon,
    ScreenshotMonitorIcon,
    CollectionsIcon,
    FormatSizeIcon,
    HtmlIcon,
    LinkIcon,
    DatasetLinkedIcon,
    AttachmentIcon,
    HorizontalRuleIcon,
    SlideshowIcon,
    WebAssetIcon,
    ViewColumnIcon,
    WallpaperIcon,
    WysiwygIcon,
    CodeIcon,
    TimelineIcon,
    HorizontalSplitIcon,
    StorageIcon,
    WidgetsIcon,
    FunctionsIcon,
    TextFormatIcon,
    PauseIcon,
    LogoutIcon,
    PreviewIcon,
    SyncIcon
} from 'gensrc/ui/admin/icons'

const iconComponents = {
    sync: SyncIcon,
    preview: PreviewIcon,
    logout: LogoutIcon,
    home: HomeIcon,
    build: BuildIcon,
    settings: SettingsIcon,
    account: AccountCircleIcon,
    edit: EditIcon,
    drive: InsertDriveFileIcon,
    folder: FolderIcon,
    subject: SubjectIcon,
    chat: ChatIcon,
    launch: LaunchIcon,
    web: WebIcon,
    cart: ShoppingCartIcon,
    image: ImageIcon,
    done: DoneIcon,
    view: ViewListIcon,
    module: ViewModuleIcon,
    label: LabelIcon,
    business: BusinessIcon,
    event: EventIcon,
    school: SchoolIcon,
    schedule: ScheduleIcon,
    shop: ShopIcon,
    beach: BeachAccessIcon,
    group: GroupIcon,
    thumbup: ThumbUpIcon,
    component: SettingsInputComponentIcon,
    train: TrainIcon,
    traffic: TrafficIcon,
    mail: MailIcon,
    member: CardMembershipIcon,
    money: MoneyIcon,
    store: StoreIcon,
    barchart: BarChartIcon,
    house: HouseIcon,
    work: WorkIcon,
    cafe: LocalCafeIcon,
    sport: SportsTennisIcon,
    accessible: AccessibleIcon,
    politics: AccountBalanceIcon,
    boat: DirectionsBoatIcon,
    filter: FilterListIcon,
    casino: CasinoIcon,
    book: BookIcon,
    save: SaveIcon,
    search: SearchIcon,
    backup: BackupIcon,
    video: VideoSettingsIcon,
    screenshot:ScreenshotMonitorIcon,
    collections:CollectionsIcon,
    format:FormatSizeIcon,
    html:HtmlIcon,
    link:LinkIcon,
    datasetLink:DatasetLinkedIcon,
    attachment:AttachmentIcon,
    horizontalRule:HorizontalRuleIcon,
    slideshow:SlideshowIcon,
    webAsset:WebAssetIcon,
    viewColum:ViewColumnIcon,
    wallpaper:WallpaperIcon,
    wysiwyg:WysiwygIcon,
    code:CodeIcon,
    timeline:TimelineIcon,
    horizontalSplit:HorizontalSplitIcon,
    storage:StorageIcon,
    widgets:WidgetsIcon,
    functions:FunctionsIcon,
    textFormat:TextFormatIcon,
    pause:PauseIcon
}

export const getIconByKey = (key, defaultIcon) => {
    return iconComponents[key] || defaultIcon
}