import React from 'react'
import {
    HomeIcon,
    BuildIcon,
    SettingsIcon,
    AccountCircleIcon,
    EditIcon,
    InsertDriveFileIcon,
    FolderIcon,
    SubjectIcon,
    CloudUploadIcon,
    ChatIcon,
    LaunchIcon,
    ShoppingCartIcon,
    WebIcon,
    ImageIcon,
    DoneIcon,
    ViewListIcon,
    ViewModuleIcon,
    LabelIcon,
    BusinessIcon,
    EventIcon,
    SchoolIcon,
    ScheduleIcon,
    ShopIcon,
    BeachAccessIcon,
    GroupIcon,
    ThumbUpIcon,
    SettingsInputComponentIcon,
    TrainIcon,
    TrafficIcon,
    MailIcon,
    CardMembershipIcon,
    MoneyIcon,
    BarChartIcon,
    StoreIcon,
    HouseIcon,
    WorkIcon,
    LocalCafeIcon,
    SportsTennisIcon,
    AccessibleIcon,
    AccountBalanceIcon,
    DirectionsBoatIcon,
    FilterListIcon,
    CasinoIcon,
    SaveIcon,
    BookIcon,
    SearchIcon,
    BackupIcon,
    VideoSettingsIcon,
    ScreenshotMonitorIcon,
    CollectionsIcon,
    FormatSizeIcon,
    HtmlIcon,
    LinkIcon,
    DatasetLinkedIcon,
    AttachmentIcon,
    HorizontalRuleIcon,
    SlideshowIcon,
    WebAssetIcon,
    ViewColumnIcon,
    WallpaperIcon,
    WysiwygIcon,
    CodeIcon,
    TimelineIcon,
    HorizontalSplitIcon,
    StorageIcon,
    WidgetsIcon,
    FunctionsIcon,
    TextFormatIcon,
    PauseIcon,
    LogoutIcon,
    PreviewIcon,
    SyncIcon,
    AddIcon,
    DisplaySettingsIcon,
    TranslateIcon,
    AutoFixHighIcon,
    CssIcon,
    JavascriptIcon,
    HistoryIcon,
    NotificationsIcon,
    SupportIcon,
    DevicesIcon,
    GridOnIcon,
    LanguageIcon,
    ReplayIcon,
    GoogleIcon,
    ShieldIcon,
    FingerprintIcon,
    DeleteIcon,
    HighlightAltIcon,
    AccountTreeIcon,
    RefreshIcon,
    QrCode2Icon,
    InputIcon,
    AddToQueueIcon,
    FolderZipIcon,
    EditNoteIcon,
    PlaylistAddIcon
} from 'gensrc/ui/admin/icons'

const iconComponents = {
    delete:DeleteIcon,
    refresh:RefreshIcon,
    magic:AutoFixHighIcon,
    translate: TranslateIcon,
    displaySetting:DisplaySettingsIcon,
    add: AddIcon,
    sync: SyncIcon,
    preview: PreviewIcon,
    logout: LogoutIcon,
    home: HomeIcon,
    build: BuildIcon,
    settings: SettingsIcon,
    account: AccountCircleIcon,
    edit: EditIcon,
    drive: InsertDriveFileIcon,
    folder: FolderIcon,
    subject: SubjectIcon,
    chat: ChatIcon,
    launch: LaunchIcon,
    web: WebIcon,
    cart: ShoppingCartIcon,
    image: ImageIcon,
    done: DoneIcon,
    view: ViewListIcon,
    module: ViewModuleIcon,
    label: LabelIcon,
    business: BusinessIcon,
    event: EventIcon,
    school: SchoolIcon,
    schedule: ScheduleIcon,
    shop: ShopIcon,
    beach: BeachAccessIcon,
    group: GroupIcon,
    thumbup: ThumbUpIcon,
    component: SettingsInputComponentIcon,
    train: TrainIcon,
    traffic: TrafficIcon,
    mail: MailIcon,
    member: CardMembershipIcon,
    money: MoneyIcon,
    store: StoreIcon,
    barchart: BarChartIcon,
    house: HouseIcon,
    work: WorkIcon,
    cafe: LocalCafeIcon,
    sport: SportsTennisIcon,
    accessible: AccessibleIcon,
    politics: AccountBalanceIcon,
    boat: DirectionsBoatIcon,
    filter: FilterListIcon,
    casino: CasinoIcon,
    book: BookIcon,
    save: SaveIcon,
    search: SearchIcon,
    backup: BackupIcon,
    video: VideoSettingsIcon,
    screenshot:ScreenshotMonitorIcon,
    collections:CollectionsIcon,
    format:FormatSizeIcon,
    html:HtmlIcon,
    link:LinkIcon,
    datasetLink:DatasetLinkedIcon,
    attachment:AttachmentIcon,
    horizontalRule:HorizontalRuleIcon,
    slideshow:SlideshowIcon,
    webAsset:WebAssetIcon,
    viewColum:ViewColumnIcon,
    wallpaper:WallpaperIcon,
    wysiwyg:WysiwygIcon,
    code:CodeIcon,
    timeline:TimelineIcon,
    horizontalSplit:HorizontalSplitIcon,
    storage:StorageIcon,
    widgets:WidgetsIcon,
    functions:FunctionsIcon,
    textFormat:TextFormatIcon,
    pause:PauseIcon,
    css: CssIcon,
    js: JavascriptIcon,
    history: HistoryIcon,
    notification: NotificationsIcon,
    support: SupportIcon,
    devices: DevicesIcon,
    upload: CloudUploadIcon,
    grid: GridOnIcon,
    replay:ReplayIcon,
    language: LanguageIcon,
    google: GoogleIcon,
    shield:ShieldIcon,
    fingerprint: FingerprintIcon,
    highlight:HighlightAltIcon,
    tree:AccountTreeIcon,
    qrcode:QrCode2Icon,
    input:InputIcon,
    addQueue:AddToQueueIcon,
    folderZip:FolderZipIcon,
    addList:PlaylistAddIcon,
    editList:EditNoteIcon
}

export const getIconByKey = (key, defaultIcon) => {
    if(key && key.constructor !== String){
        return defaultIcon || key
    }
    return iconComponents[key] || defaultIcon
}