/*
 Here are all user capabilities listed
 */

export const CAPABILITY_VIEW_APP = 'view_app'
export const CAPABILITY_ACCESS_ADMIN_PAGE = 'access_admin_page'
export const CAPABILITY_MANAGE_TYPES = 'manage_types'
export const CAPABILITY_MANAGE_CMS_PAGES = 'manage_cms_pages'
export const CAPABILITY_MANAGE_KEYVALUES = 'manage_keyvalues'
export const CAPABILITY_MANAGE_OTHER_USERS = 'manage_other_users'
export const CAPABILITY_MANAGE_COLLECTION = 'manage_collection'
export const CAPABILITY_MANAGE_USER_ROLE = 'manage_user_role'
export const CAPABILITY_MANAGE_BACKUPS = 'manage_backups'
export const CAPABILITY_READ_EVERYTHING = 'read_everything'
export const CAPABILITY_RUN_COMMAND = 'run_command'
export const CAPABILITIES = [CAPABILITY_VIEW_APP, CAPABILITY_ACCESS_ADMIN_PAGE, CAPABILITY_MANAGE_TYPES, CAPABILITY_MANAGE_CMS_PAGES, CAPABILITY_MANAGE_KEYVALUES, CAPABILITY_MANAGE_OTHER_USERS, CAPABILITY_MANAGE_COLLECTION, CAPABILITY_MANAGE_USER_ROLE, CAPABILITY_MANAGE_BACKUPS, CAPABILITY_READ_EVERYTHING, CAPABILITY_RUN_COMMAND]